/// Flutter icons IconSet
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconSet
///      fonts:
///       - asset: fonts/IconSet.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class IconSet {
  IconSet._();

  static const _kFontFam = 'IconSet';
  static const _kFontPkg = null;

  static const IconData write = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_button = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom_one = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom_three = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bottom_two = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clip = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_icon = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData message = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_button = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toggle = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData three_dots = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo_1 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smiley_face = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exclamation = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
